# ----
# Site

title: go.PANTHEON.tech
url: "https://go.pantheon.tech"
baseurl: "" 

author:
  name: PANTHEON.tech
  email: info@pantheon.tech
  twitter: Pantheon_Tech
social:
  name: PANTHEON.tech
  links:
    - https://pantheon.tech

# -----
# Build

permalink: "/:title"

exclude:
  - Gemfile
  - Gemfile.lock
